version: "3.7"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.0
    container_name: filebeat
    volumes:
      - './filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - './volumes/filebeat/data:/usr/share/filebeat/data:rw'
      - './volumes/sniffer/network.log:/usr/share/filebeat/sniffer/network.log'
    command: filebeat -e -strict.perms=false
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - ${GLOBAL_NETWORK:-kafka}