version: "3.7"

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    container_name: logstash
    restart: unless-stopped
    volumes:
      - "./elk/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
#    depends_on:
#      - elasticsearch
    networks:
      - ${GLOBAL_NETWORK:-kafka}