packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 5s
  period: 2s

#output.console:
#  pretty: true

#output.kafka:
#  version: 0.10.2.1
#  hosts: ["kafka-broker-1:9092"]
#  topic: 'packetbeat-logs'
#  partition.round_robin:
#    reachable_only: false
#  required_acks: 1
#  compression: gzip
#  max_message_bytes: 1000000

output.kafka:
  hosts: ["kafka-broker-1:9092", "kafka-broker-2:9092", "kafka-broker-3:9092"]
  topic: 'packetbeat-logs'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000